# -*- coding: utf-8 -*-
"""stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sajDjkZHuprrBibKyjpzD-TQnNohjDYS
"""



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

data = yf.download("AAPL", start="2015-01-01", end="2024-01-01")

data = data[['Close']]
data.head()

plt.figure(figsize=(10,6))
plt.plot(data['Close'])
plt.title("Stock Price History")
plt.xlabel("Date")
plt.ylabel("Price")
plt.show()

scaler = MinMaxScaler(feature_range=(0,1))

scaled_data = scaler.fit_transform(data)

X_train = []
y_train = []

for i in range(60, len(scaled_data)):
    X_train.append(scaled_data[i-60:i,0])
    y_train.append(scaled_data[i,0])

X_train, y_train = np.array(X_train), np.array(y_train)

X_train = np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))

model = Sequential()

model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1],1)))
model.add(LSTM(units=50))

model.add(Dense(25))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')

model.fit(X_train, y_train, batch_size=32, epochs=10)

look_back = 60

# Create a new test_data that includes the last 'look_back' values from the training set
# plus the actual test set (which is `valid` and has 60 elements).
# `len(data)-60` is the split point between training and validation data.
# So, `scaled_data[len(scaled_data) - look_back:]` is not correct,
# as `len(scaled_data)` refers to the total dataset length.
# We need the portion of `scaled_data` that will be used to generate X_test sequences
# for predicting the `valid` set. The `valid` set has 60 elements.
# To predict the first element of `valid`, we need the 60 elements before it.
# So, the test data for prediction should start `look_back` days before the `valid` set.
# The `valid` set starts at index `len(scaled_data) - 60`.
# Thus, the data needed starts at index `len(scaled_data) - 60 - look_back`.

# The original `valid` set from the plotting cell is `data[len(data)-60:]`.
# In scaled terms, this is `scaled_data[len(scaled_data)-60:]` and has 60 elements.
# We need `look_back` (60) days prior to the start of this 60-day period.
# So, total data needed = `look_back` (for input sequences) + `len(valid)` (for the values to predict).
# Total length required = 60 + 60 = 120.
# This means we should take `scaled_data` from index `len(scaled_data) - 120` onwards.

test_data_for_prediction = scaled_data[len(scaled_data) - (len(data) - (len(data) - 60)) - look_back:]

# Re-evaluating the above line for clarity and correctness based on previous cells:
# The `valid` set corresponds to `scaled_data[len(scaled_data)-60:]`. Let's call its length `len_valid = 60`.
# To predict these `len_valid` values, each prediction requires a `look_back` window.
# So, the input data for making predictions on the `valid` set should be:
# `scaled_data[len(scaled_data) - look_back - len_valid : ]`
# Which is `scaled_data[2264 - 60 - 60 : ] = scaled_data[2144:]`

# So, `test_data_for_prediction` should have a length of 120.
test_data_for_prediction = scaled_data[len(scaled_data) - look_back - 60:]

X_test = []

# The loop should start from `look_back` to create the first sequence
# for the first prediction in the actual test set.
for i in range(look_back, len(test_data_for_prediction)):
    X_test.append(test_data_for_prediction[i-look_back:i,0])

X_test = np.array(X_test)

# The reshape will now work correctly as X_test will not be empty
X_test = np.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

predictions = model.predict(X_test)

predictions = scaler.inverse_transform(predictions)

train = data[:len(data)-60]
valid = data[len(data)-60:]

valid['Predictions'] = predictions

plt.figure(figsize=(12,6))
plt.title('Stock Price Prediction')
plt.xlabel('Date')
plt.ylabel('Price')

plt.plot(train['Close'])
plt.plot(valid[['Close','Predictions']])

plt.legend(['Train','Actual','Predicted'])

plt.show()